mutation CreateUser($data: CreateUserInput!) {
  createUser(data: $data) {
    token
    user {
      email
      firstName
      id
      lastName
      verified
      userName
      avatar
    }
  }
}
